version: '3.7'

services:
  nodejs:
    build:
      dockerfile: Dockerfile-Prod
    ports:
      - '3000:3000'
    restart: on-failure
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - node_modules_frontend:/home/node/app/packages/frontend/node_modules
      - build_output:/home/node/app/packages/frontend/build
    command: >
      sh -c "
             node /home/node/app/packages/frontend/build/index.js"

volumes:
  node_modules:
  node_modules_frontend:
  build_output:
