version: '3.7'

services:
  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile-Nodejs
    image: node:18.12.1-alpine3.15
    ports:
      - '5000:5000'
    container_name: nodejs
    volumes:
      - ./nodejs:/home/node/app
    networks:
      - app-network
    command: npm run lerna-dev
  python:
    build:
      context: ./python/backend
      dockerfile: Dockerfile-Python
    image: python:3.11.0-alpine3.17
    restart: on-failure
    env_file: .env
    ports:
      - '8080:8080'
    container_name: python
    volumes:
      - ./python/backend:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
