openapi: 3.0.0
info:
  title: 'RP Flask REST API'
  description: 'A small API to send contact email'
  version: '1.0.0'

servers:
  - url: '/api'

components:
  schemas:
    Applicant:
      type: 'object'
      required:
        - fname
        - email
        - message
        - locale
      properties:
        fname:
          type: 'string'
          pattern: '^(\s|\w){4,30}$'
        email:
          type: 'string'
          pattern: '^[^@]+[@][a-zA-Z]+\.[a-zA-Z]+'
        message:
          type: 'string'
          pattern: '^.{3,50}$'
        locale:
          type: 'string'
          pattern: '^(es-ES)|(en-US)$'

paths:
  /applicant:
    post:
      operationId: 'applicant.send_email'
      tags:
        - Applicant
      summary: 'Send request email'
      requestBody:
        description: 'Email data fields'
        required: True
        content:
          application/json:
            schema:
              x-body-name: 'applicant'
              $ref: '#/components/schemas/Applicant'
      responses:
        '200':
          description: 'Email send succesfully'
