openapi: 3.0.0
info:
  title: 'RP Flask REST API'
  description: 'An API about people and notes'
  version: '1.0.0'

servers:
  - url: '/api'

components:
  schemas:
    Applicant:
      type: 'object'
      required:
        - fname
        - email
        - message
      properties:
        fname:
          type: 'string'
        email:
          type: 'string'
        message:
          type: 'string'

paths:
  /applicant:
    post:
      operationId: 'applicant.send_email'
      tags:
        - Applicant
      summary: 'Send request email'
      requestBody:
        description: 'Email data fields'
        required: True
        content:
          application/json:
            schema:
              x-body-name: 'applicant'
              $ref: '#/components/schemas/Applicant'
      responses:
        '200':
          description: 'Email send succesfully'
